resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: pr-concourse-test
  type: pull-request
  source:
    repo: halimacc/pr-concourse-test
    access_token: {{github_access_token}}
    private_key: {{git_private_key}}
    every: true

jobs:
- name: job1
#  serial_groups: ['job2', 'job3']
  plan:
  - get: pr-concourse-test
    trigger: true
    version: every
  - task: do something with git
    config:
      platform: linux
      image: docker:///concourse/git-resource
      run:
        path: sh
        args:
        - -c
        - cd pr-concourse-test && sleep 15 && git --no-pager show
      inputs:
      - name: pr-concourse-test
        path: ""

# - name: job2
#   serial_groups: ['job2']
#   plan:
#   - get: pr-concourse-test
#     trigger: true
#     version: 'every'
#     passed: ['job1']
#   - task: do something with git
#     config:
#       platform: linux
#       image: docker:///concourse/git-resource
#       run:
#         path: sh
#         args:
#         - -c
#         - cd pr-concourse-test && sleep 30 && git --no-pager show
#       inputs:
#       - name: pr-concourse-test
#         path: ""

# - name: job3
#   serial_groups: ['job3']
#   plan:
#   - get: pr-concourse-test
#     trigger: true
#     version: 'every'
#     passed: ['job1']
#   - task: do something with git
#     config:
#       platform: linux
#       image: docker:///concourse/git-resource
#       run:
#         path: sh
#         args:
#         - -c
#         - cd pr-concourse-test && sleep 15 && git --no-pager show
#       inputs:
#       - name: pr-concourse-test
#         path: ""

