resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: pr-concourse-test
  type: pull-request
  source:
    repo: halimacc/pr-concourse-test
    access_token: {{github_access_token}}
    private_key: {{git_private_key}}
    every: true

- name: git-concourse-test
  type: git
  source:
    uri: git@github.com:halimacc/pr-concourse-test
    branch: master
    private_key: {{git_private_key}}

jobs:
- name: job1
  plan:
  - get: git-concourse-test
    trigger: true
  - task: do something with git
    config:
      platform: linux
      image: docker:///concourse/git-resource
      run:
        path: sh
        args:
        - -c
        - cd git-concourse-test && sleep 60 && git --no-pager show
      inputs:
      - name: git-concourse-test
        path: ""