resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: pr-concourse-test
  type: pull-request
  source:
    repo: halimacc/pr-concourse-test
    access_token: {{github_access_token}}
    private_key: {{git_private_key}}

jobs:
- name: test pull request
  plan:
  - get: pr-concourse-test
    trigger: true
  - put: pr-concourse-test
    params:
      path: pr-concourse-test
      status: pending
  - task: do something with git
    config:
      platform: linux
      image: docker:///concourse/git-resource
      run:
        path: sh
        args:
        - -c
        - cd pr-concourse-test && sleep 180 && git --no-pager show
      inputs:
      - name: pr-concourse-test
        path: ""
    on_success:
      put: pr-concourse-test
      params:
        path: pr-concourse-test
        status: success
    on_failure:
      put: pr-concourse-test
      params:
        path: pr-concourse-test
        status: failure